### ISSUE TITLE
Убрать комментарии в тесте CharacterDisplay.spec.ts

### ISSUE THREAD

**Issue by Tolgran** [Shavius/team_project#26]
Убрать комментарии в тесте CharacterDisplay.spec.ts

**Comment by Shavius** [comment]
давай

**Comment by Kangern** [comment]
> Убрать комментарии в тесте CharacterDisplay.spec.ts

А для чего ?

**Comment by Tolgran** [comment]
> > Убрать комментарии в тесте CharacterDisplay.spec.ts
> 
> А для чего ?

Я убрал тесты из ESlint и те комментарии больше не нужны

**Comment by Kangern** [comment]
> > > Убрать комментарии в тесте CharacterDisplay.spec.ts
> > 
> > 
> > А для чего ?
> 
> Я убрал тесты из ESlint и те комментарии больше не нужны

Ок понял
